import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {readFile} from 'node:fs/promises';
import {mountHub} from '../site/hub.js';
import {emptyState,normalize,addSnapshot} from '../site/model.js';
const originalFetch=globalThis.fetch;
const tick=()=>new Promise(r=>setTimeout(r,20));
function setup(){const dom=new JSDOM('<div id="root"></div><dialog id="modal"></dialog>',{url:'https://forever.dudgeon.io/'});globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.location=dom.window.location;globalThis.FormData=dom.window.FormData;globalThis.fetch=async url=>({ok:true,json:async()=>JSON.parse(await readFile('site/'+url.replace(/^\.\//,''),'utf8'))});let state=addSnapshot(emptyState(),normalize({name:'Guuko Gravemoor',realm:'Normal',class:'PALADIN',level:13,source:'addon',inventory:[{id:2770,name:'Copper Ore',count:12}]})).state;const calls=[];const api={editor:async()=>true,published:async()=>[],myContributions:async()=>[],pending:async()=>[],contribute:async d=>calls.push(['contribute',d]),guild:async()=>({id:'test',name:'Test Guild',description:'Recruiting',faction:'Horde',playStyle:'Normal',ownerUid:'alice',memberUids:['alice','bob'],officerUids:[]}),guildRecords:async()=>[{id:'event1',ownerUid:'alice',kind:'event',payload:JSON.stringify({title:'Dungeon night',starts:'2026-10-01T20:00:00Z',notes:'Repair first'})}],requests:async()=>[{uid:'carol',name:'Carol'}],record:async(...args)=>calls.push(['record',...args]),membership:async(...args)=>calls.push(['membership',...args]),guilds:async()=>[],createGuild:async d=>{calls.push(['create',d]);return 'newguild';}};
const ctx={current:()=>state,account:()=>({uid:'alice',name:'Alice'}),community:()=>api,commit:async n=>{state=n;},toast:m=>calls.push(['toast',m]),refresh:()=>calls.push(['refresh']),modal:(title,body,bind)=>{document.querySelector('#modal').innerHTML=body;document.querySelector('#modal').close=()=>{};bind();}};return {dom,root:document.querySelector('#root'),ctx,calls,api};}
function submit(dom,form){form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));}
test('hub DOM routes and private inventory render safely',async()=>{const {root,ctx,dom}=setup();await mountHub(root,'database',null,ctx);assert.match(root.textContent,/Coverage is incomplete/);const search=root.querySelector('#catalog-query');search.value='Copper Ore';search.dispatchEvent(new dom.window.Event('input'));assert.match(root.querySelector('#catalog-results').textContent,/Personal import/);await mountHub(root,'database','item%3A6220',ctx);assert.match(root.textContent,/Meteor Shard/);await mountHub(root,'classes','paladin',ctx);assert.equal(root.querySelector('a[href="#talents/paladin"]').textContent,'Open Paladin talent planner');await mountHub(root,'inventory',null,ctx);assert.match(root.textContent,/Copper Ore/);assert.match(root.textContent,/12 units observed/);dom.window.close();});
test('guild share, event, membership and RSVP handlers survive final rendering',async()=>{const {root,ctx,dom,calls}=setup();await mountHub(root,'guilds','test',ctx);submit(dom,root.querySelector('#share-character'));await tick();const share=calls.find(c=>c[0]==='record'&&c[2]==='roster');assert.ok(share);assert.equal(share[3].name,'Guuko Gravemoor');assert.equal(share[3].inventory,undefined);assert.equal(share[3].accountId,undefined);root.querySelector('[data-action="approve"]').click();await tick();assert.ok(calls.some(c=>c[0]==='membership'&&c[2]==='carol'&&c[3]==='approve'));submit(dom,root.querySelector('[data-rsvp]'));await tick();assert.ok(calls.some(c=>c[0]==='record'&&c[2]==='rsvp'&&c[3].eventId==='event1'));const form=root.querySelector('#guild-event');form.elements.title.value='Raid';form.elements.starts.value='2026-10-01T20:00';submit(dom,form);await tick();assert.ok(calls.some(c=>c[0]==='record'&&c[2]==='event'&&c[3].title==='Raid'));assert.equal(root.querySelector('.hub-error'),null);dom.window.close();});
test('contribution submits evidence and rejects executable links',async()=>{const {root,ctx,dom,calls}=setup();await mountHub(root,'community',null,ctx);const form=root.querySelector('#contribute');form.elements.title.value='<img src=x onerror=alert(1)>';form.elements.body.value='Observed drop';form.elements.source.value='javascript:alert(1)';submit(dom,form);await tick();assert.ok(!calls.some(c=>c[0]==='contribute'));form.elements.source.value='https://example.com/evidence';submit(dom,form);await tick();assert.ok(calls.some(c=>c[0]==='contribute'));assert.equal(root.querySelector('img'),null);dom.window.close();});
test('guild bank requires a scope and stores only validated items',async()=>{const {root,ctx,dom,calls}=setup();await mountHub(root,'guilds','test',ctx);const form=root.querySelector('#guild-bank');form.elements.snapshot.value=JSON.stringify({location:'guild-bank',scopeId:'Test:tab1',observedAt:'2026-09-28',items:[{id:2770,name:'Copper Ore',count:3}]});submit(dom,form);await tick();assert.ok(calls.some(c=>c[0]==='record'&&c[2]==='bank'&&c[3].scopeId==='Test:tab1'));dom.window.close();});
test.after(()=>{globalThis.fetch=originalFetch;});
