import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,saveManualCharacter,addSnapshot,normalize,validateBackup,keyOf,mergeBackup} from '../site/model.js';
import {CHALLENGES,earnedChallenges,legacyPoints,setPerkRank,perkTotal} from '../site/legacy.js';
import {recordsFor,stateFromRecords} from '../site/cloud-model.js';
const fields={mainName:'Asha',secondaryName:'Brightvale',playStyle:'Normal',class:'PALADIN',level:25,faction:'Horde',race:'Undead',professions:[]};
test('65 challenges and one shared pool across separate game accounts',()=>{assert.equal(CHALLENGES.length,65);let s=emptyState();s.gameAccounts.push({id:'wow2',name:'WoW 2'});s=saveManualCharacter(s,fields).state;s=saveManualCharacter(s,{...fields,accountId:'wow2'}).state;assert.equal(s.characters.length,2);assert.notEqual(s.characters[0].id,s.characters[1].id);assert.equal(legacyPoints(s),1);s=setPerkRank(s,s.characters[0].id,'well-rested',1);s=setPerkRank(s,s.characters[1].id,'working-overtime',1);assert.equal(perkTotal(s.legacy.perks[s.characters[0].id]),1);assert.equal(perkTotal(s.legacy.perks[s.characters[1].id]),1);assert.throws(()=>setPerkRank(s,s.characters[0].id,'bartering',1));});
test('class and non-gathering tradeskill milestones infer only confirmed points',()=>{let s=emptyState();s=addSnapshot(s,normalize({...fields,level:45,professions:[{name:'Blacksmithing',rank:225},{name:'Mining',rank:300}]})).state;assert.deepEqual([...earnedChallenges(s)].sort(),['class-paladin-25','class-paladin-45','trade-blacksmithing-150','trade-blacksmithing-225']);assert.equal(legacyPoints(s),4);});
test('legacy account and character plans survive cloud and backup, old data migrates',async()=>{let s=emptyState();s.gameAccounts.push({id:'wow2',name:'WoW 2'});s=saveManualCharacter(s,{...fields,accountId:'wow2'}).state;s.legacy.challenges.push('explore-world');s=setPerkRank(s,s.characters[0].id,'well-rested',1);const round=stateFromRecords([...(await recordsFor(s)).values()]);assert.deepEqual(round,validateBackup({format:'forever-armory-backup',...s}));let old=validateBackup({format:'forever-armory-backup',version:1,characters:[],tasks:[]});assert.equal(old.gameAccounts[0].id,'default');assert.equal(mergeBackup(old,s).characters[0].id,s.characters[0].id);});
test('Hardcore does not spend non-Hardcore pool',()=>{let s=saveManualCharacter(emptyState(),{...fields,playStyle:'Hardcore'}).state;s.legacy.challenges.push('explore-world');assert.throws(()=>setPerkRank(s,s.characters[0].id,'well-rested',1));assert.equal(legacyPoints(s),1);});
